### ISSUE TITLE
Add an Open Source License

### ISSUE THREAD

**Issue by fer-correa** [cadu-leite/pgsrchcorrupt#5]
Hi @cadu-leite ,
It would be great if this project had an Open Source license so that the community knows how to consume and contribute to it. What do you think??
MIT or BSD-3-Clause will be great 😄

**Comment by cadu-leite** [comment]
done 
18f7b46cb546f2e4a9b1be5b3b7bf92b8800b043

**Comment by cadu-leite** [comment]
done 18f7b46cb546f2e4a9b1be5b3b7bf92b8800b043
